ci: refactor dockerfiles moving to alpine linux

diff --git a/dockerfiles/dockerfile-samgis-base b/dockerfiles/dockerfile-samgis-base
--- a/dockerfiles/dockerfile-samgis-base
+++ b/dockerfiles/dockerfile-samgis-base
@@ -2,7 +2,7 @@
 ARG ARCH="x86_64"
 ARG WORKDIR_ROOT="/var/task"
 ARG FASTAPI_STATIC="${WORKDIR_ROOT}/static"
-ARG PYTHONPATH="${WORKDIR_ROOT}:${PYTHONPATH}:/usr/local/lib/python3/dist-packages"
+ARG PYTHONPATH="${WORKDIR_ROOT}:${PYTHONPATH}:/usr/local/lib/python3.12/dist-packages:/usr/lib/python3.12/site-packages"
 ARG POETRY_NO_INTERACTION=1
 ARG POETRY_VIRTUALENVS_IN_PROJECT=1
 ARG POETRY_VIRTUALENVS_CREATE=1
@@ -10,64 +10,82 @@ ARG POETRY_CACHE_DIR=/tmp/poetry_cache
 ARG HOME_USER=/home/python
 
 
-FROM python:3.12-trixie AS builder_global
+FROM python:3.12-alpine3.23 AS builder_global
 
 ARG ARCH
-ARG WORKDIR_ROOT
-ARG PYTHONPATH
+ARG WORKDIR_ROOT="/var/task"
 ARG POETRY_NO_INTERACTION
 ARG POETRY_VIRTUALENVS_IN_PROJECT
 ARG POETRY_VIRTUALENVS_CREATE
 ARG POETRY_CACHE_DIR
+ARG PYTHONPATH
 
 RUN echo "ARCH: $ARCH ..."
 
 RUN echo "ARG POETRY_CACHE_DIR: ${POETRY_CACHE_DIR} ..."
 RUN echo "ARG PYTHONPATH: $PYTHONPATH ..."
+RUN echo "ARG WORKDIR_ROOT: ${WORKDIR_ROOT} ..."
 RUN echo "arg dep:"
 
-RUN groupadd -g 999 python && useradd -r -u 999 -g python python
+RUN addgroup --gid 9988 python && adduser --system --uid 9988 -G python python
 # Set working directory to function root directory
 RUN mkdir ${WORKDIR_ROOT} && chown python:python ${WORKDIR_ROOT}
 WORKDIR ${WORKDIR_ROOT}
-COPY --chown=python:python requirements_poetry.txt pyproject.toml poetry.lock README.md ${WORKDIR_ROOT}/
+RUN ls -l ${WORKDIR_ROOT}
+RUN ls -ld ${WORKDIR_ROOT}
+
+COPY --chown=python:python requirements_poetry.txt requirements_failed.txt pyproject.toml poetry.lock README.md ${WORKDIR_ROOT}/
 
 # avoid segment-geospatial exception caused by missing libGL.so.1 library
-RUN apt update && apt install -y libgl1 curl python3-pip libexpat1 && apt clean
+# rasterio doesn't work on alpine linux without gdal-dev
+RUN apk update && apk add mesa-gl py3-onnxruntime curl gdal-dev gcc musl-dev g++ && apk cache clean
 
 # poetry installation path is NOT within ${WORKDIR_ROOT}: not needed for runtime docker image
-RUN python -m pip install -r ${WORKDIR_ROOT}/requirements_poetry.txt
+RUN python -m pip install --upgrade pip \
+    && python -m pip install -r ${WORKDIR_ROOT}/requirements_poetry.txt && python -m pip list
+RUN python3 -m venv ${WORKDIR_ROOT}/.venv && . ${WORKDIR_ROOT}/.venv/bin/activate
+RUN echo "# WORKDIR_ROOT: ${WORKDIR_ROOT} #"
+RUN ls -ld ${WORKDIR_ROOT}
+RUN ls -ltrA ${WORKDIR_ROOT}/.venv/
+RUN ls -ld ${WORKDIR_ROOT}/.venv/
 
-RUN which poetry && poetry --version && poetry config --list
-RUN poetry config virtualenvs.path ${WORKDIR_ROOT}
-RUN echo "# poetry config --list #" && poetry config --list
-RUN poetry install --no-cache
+RUN . ${WORKDIR_ROOT}/.venv/bin/activate && poetry config virtualenvs.path ${WORKDIR_ROOT}
+RUN . ${WORKDIR_ROOT}/.venv/bin/activate && echo "# poetry config --list #" && poetry config --list
+RUN . ${WORKDIR_ROOT}/.venv/bin/activate && poetry install --no-cache || echo "error on python package installation"
+RUN . ${WORKDIR_ROOT}/.venv/bin/activate && pip wheel --no-cache-dir --use-pep517 -r requirements_failed.txt
+
+RUN . ${WORKDIR_ROOT}/.venv/bin/activate && for p in $(cat requirements_failed.txt ); do \
+    pp=$(echo $p|cut -d'=' -f1); echo "# Installing wheel for ${pp} #"; pip install ${pp}*.whl; done
+RUN . ${WORKDIR_ROOT}/.venv/bin/activate && python -c "import onnxruntime;import rasterio"
 
 
-FROM python:3.12-slim-trixie AS runtime
+FROM python:3.12-alpine3.23 AS runtime
 
 ARG ARCH
 ARG WORKDIR_ROOT
 ARG HOME_USER
+ARG PYTHONPATH
 
 ENV VIRTUAL_ENV=${WORKDIR_ROOT}/.venv PATH="${WORKDIR_ROOT}/.venv/bin:$PATH"
 
 # workaround for missing /home folder
-RUN mkdir -p /home
-RUN groupadd -g 999 python && useradd -r -u 999 -g python python
-RUN ls -l /home
-RUN ls -ld /home
-RUN mkdir -p ${HOME_USER} ${HOME_USER}/.config && chown python:python -R ${HOME_USER}
+RUN ls -ld /home && addgroup --gid 9988 python && adduser --system --uid 9988 -G python python
+RUN ls -l /home && mkdir -p ${HOME_USER} ${HOME_USER}/.config && chown python:python -R ${HOME_USER}
 RUN ls -ld ${HOME_USER}
 RUN ls -lA ${HOME_USER}
 RUN mkdir ${WORKDIR_ROOT} && chown python:python ${WORKDIR_ROOT}
 
-RUN echo "RUNTIME: check libexpat.so*, libGL.so* before start" && ls -l /usr/lib/${ARCH}-linux-gnu/libexpat.so* /usr/lib/${ARCH}-linux-gnu/libGL.so* || echo "libraries libexpat.so*, libGL.so* not found"
-COPY --from=builder_global /usr/lib/${ARCH}-linux-gnu/libGL.so* /usr/lib/${ARCH}-linux-gnu/
-COPY --from=builder_global /lib/${ARCH}-linux-gnu/libexpat.so* /lib/${ARCH}-linux-gnu/
-RUN echo "RUNTIME: check libexpat.so*, libGL.so* after copy" && ls -l /usr/lib/${ARCH}-linux-gnu/libexpat.so* /usr/lib/${ARCH}-linux-gnu/libGL.so*
+RUN apk update && apk add py3-onnxruntime gdal-dev && apk cache clean
+
+RUN echo "RUNTIME: check libexpat.so*, libGL.so* before start" && ls -l /usr/lib/libexpat.so* /usr/lib/libGL.so* \
+    || echo "libraries libexpat.so*, libGL.so* not found"
+COPY --from=builder_global /usr/lib/libGL.so* /usr/lib/
+COPY --from=builder_global /usr/lib/libexpat.so* /usr/lib/
+RUN echo "RUNTIME: check libexpat.so*, libGL.so* after copy" && ls -l /usr/lib/libGL.so* /usr/lib/libexpat.so*
 COPY --from=builder_global ${WORKDIR_ROOT}/.venv ${WORKDIR_ROOT}/.venv
 RUN . ${WORKDIR_ROOT}/.venv && which python && pip list
+
+COPY --chown=python:python ./app.py ./scripts/health.py ${WORKDIR_ROOT}/
 
 RUN echo "new WORKDIR_ROOT after hidden venv copy => ${WORKDIR_ROOT}"
 RUN ls -ld ${WORKDIR_ROOT}/
@@ -75,7 +93,7 @@ RUN ls -lA ${WORKDIR_ROOT}/
 
 
 ### conditional section
-FROM node:22-slim AS node_fastapi
+FROM node:24-alpine AS node_fastapi
 
 ENV PNPM_HOME="/pnpm"
 ENV PATH="$PNPM_HOME:$PATH"
@@ -103,12 +121,14 @@ RUN echo "VITE__INDEX_URL:" ${VITE__INDEX_URL}
 
 RUN --mount=type=cache,id=pnpm,target=/pnpm/store; pnpm install --frozen-lockfile
 RUN --mount=type=cache,id=pnpm,target=/pnpm/store; pnpm build
-RUN --mount=type=cache,id=pnpm,target=/pnpm/store; pnpm dlx @tailwindcss/cli -i /appnode/src/input.css -o /appnode/dist/output.css
+RUN --mount=type=cache,id=pnpm,target=/pnpm/store; \
+    pnpm dlx @tailwindcss/cli -i /appnode/src/input.css -o /appnode/dist/output.css
 RUN if [ ! -d /appnode/dist ]; then echo "no dist folder" && exit 1; fi
 
 
 FROM runtime
 ARG FASTAPI_STATIC
+ARG WORKDIR_ROOT
 
 RUN mkdir ${FASTAPI_STATIC} && chown python:python ${FASTAPI_STATIC}
 
